config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home_copywriting', as: :home_copywriting
  get '/about', to: 'pages#about', as: :about
  get '/contact', to: 'pages#contact', as: :contact
  get '/blog', to: 'pages#blog', as: :blog
  get '/portfolio', to: 'pages#portfolio', as: :portfolio
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def portfolio

  @examples = [
    {
      name: "Facebook Ad",
      class_name: "clearcut",
      brief: "Facebook ad post for productivity software <span class=\"clearcut\">clearcut</span>.",
      alt: "Image of Clearcut poster.",
      image_link: "clearcut-ad.png",
      description: "Selling products in the SaaS space is almost like a competitive sport.\n\nBecause of the range of products on offer, it's really important to make sure your ad puts your product's unique selling point front and centre.\n\nIn this Facebook post, creating the story of Dave highlighted the solution to a common pain point that many businesses face: inefficient workflows."
    },
    {
      name: 'Landing Page',
      class_name: 'my-mode',
      label: "Click here to visit my-mode.art",
      link: 'https://www.my-mode.art',
      image_link: 'my-mode-image.png',
      alt: "Image of My Mode landing page.",
      brief: 'Landing page copy for fashion social media site <span class="my-mode">my mode</span>.',
      description: "With any social media site, drawing in customers requires you to give customers an experience unmatched by any other platform.\n\nFor the work on this landing page, I accomplished this by focusing on three themes relevant to fashion: individuality, boldness and community."
    },
    {
      name: 'Email Newsletter',
      class_name: 'newsletter',
      alt: "Image of email newsletter for short story socal network nuvell.",
      brief: 'An email newsletter designed to showcase short story platform nuvell.',
      image_link: 'email-newsletter1.png',
      description: " Email newsletters can really help you enhance customer retention. By providing them with regular and personalised updates, you can keep them engaged.\n\nBecause this is a site designed to share short stories, I wanted a newsletter that would provide readers with tips and tricks to help them improve their writing."
    },
    {
      name: 'Marketing Blog',
      class_name: 'blog',
      label: "Click here to see my Medium post on marketing tips for 2023",
      alt: 'Image of Medium page for blog post.',
      brief: 'A blog designed to help you improve your marketing strategies for 2023.',
      link: 'https://medium.com/@three-marketers/advertising-in-2023-9a76d7c19361',
      image_link: 'blog-example.png',
      description: "Audiences <em>love</em> long form content, but they also need it to be digestible, especially if you're reading it on a screen. A blog is great way to communicate those ideas.\n\nBy providing marketers with a list of dos and dont's to remember for 2023, they'll be well equipped to handle whatever the new year throws at them."
    }
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
   <head>
      <title><%= meta_title %></title>
</script>

      <meta name="description" content="<%= meta_description %>">
      <!-- Facebook Open Graph data -->
      <meta property="og:title" content="<%= meta_title %>" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="<%= request.original_url %>" />
      <meta property="og:image" content="<%= meta_image %>" />
      <meta property="og:description" content="<%= meta_description %>" />
      <meta property="og:site_name" content="<%= meta_title %>" />
      <!-- Twitter Card data -->
      <meta name="twitter:card" content="summary_large_image">
      <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
      <meta name="twitter:title" content="<%= meta_title %>">
      <meta name="twitter:description" content="<%= meta_description %>">
      <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
      <meta name="twitter:image:src" content="<%= meta_image %>">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= favicon_link_tag %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
   </head>
   <body>
      <nav class="navbar nav-transparent fixed-top">
         <div style="display:flex;flex-direction:column;">
            <%= link_to (image_tag "antshawlogo.svg", class: "logo", alt: "Image of Ant Shaw logo. All rights reserved."), '/', class: "nav-link", aria_label: "Click to return to the home page.", rel: "noopener" %>
         <%# <div style="background:black;height:1px;width:10px;"></div> %>
         </div>
         <div>
            <%= link_to "About", 'about', class:"nav-link", rel:'noopener' %>
         </div>
         <div>
            <%= link_to "Portfolio", 'portfolio', class:"nav-link text-center", rel:'noopener' %>
         </div>
         <div>
            <%= link_to "Contact", 'contact', class:"nav-link", rel:'noopener' %>
         </div>
         <!---<%= link_to "Blog", 'blog', class:"nav-link", rel:'noopener' %>--->
      </nav>
      <div class="flex-wrapper">
        <%= yield %>
        <%# <div class='arrow-box' id="arrow-box">
            <svg width="50" height="22" viewBox="0 0 50 22" fill="none" xmlns="http://www.w3.org/2000/svg" class="arrow" id="navigation-arrow">
               <line x1="1.40578" y1="2.93268" x2="26.4058" y2="19.9327" stroke="black" stroke-width="5"/>
               <line y1="-2.5" x2="30.2324" y2="-2.5" transform="matrix(-0.826927 0.56231 0.56231 0.826927 50 5)" stroke="black" stroke-width="5"/>
            </svg>
        </div> %>
      </div>
   </body>
</html>

app/views/pages/about.html.erb
<div class="flx-container">
    <div class="text-center my-5 mt-5">
        <div class="translate">
            <h1 class="home-title" style="margin-left: 32px;">ABOUT</h1>
            <div class="arrow-box" id="arrow-box">
                  <%= image_tag 'arrow.svg', alt: "Image of navigation arrow." %>
            </div>
        </div>
    </div>
</div>
<div class="container-page">
<hr>
    <div>
   <h2 class="about-h2">Advertising is like baking a cake.</h2>
    </div>
    <div class="about-section">
      <div class="flex-end">
        <%= image_tag 'cake.svg' %>
      </div>
      <div>
        <p>A cake can often look good when you add icing, sprinkles and a cherry on top.</p>
        <p>Likewise, we can often spruce up an ad with expensive video testimonials, glossy images and stunning vector graphics.</p>
      </div>
    </div>
    <div class="about-section">
      <div class="flex-start">
        <p>But without the foundations to match, neither your ad (or cake) are likely to hold together.</p>
      </div>
      <div>
        <%= image_tag 'flour.svg' %>
      </div>
    </div>
    <div class="about-section">
      <div>
        <%= image_tag "copywriting.svg" %>
      </div>
      <div class="flex-start">
        <p>That's where I come in. As a creative copywriter, I can help you build the perfect ad.</p>
        <p>Whether it's a Facebook post, a email newsletter or words to help your landing page, you'll get top-quality writing for reasonable prices.</p>
        <p><%=link_to "Check out my portfolio for some examples!", "/portfolio#portfolio-examples" %></p>
      </div>
    </div>
    <div class="about-section">
        <div id="flex-start">
        
        </div>
    </div>
</div>

app/views/pages/blog.html.erb
<h1>Blog</h1>

app/views/pages/contact.html.erb
<div class="flx-container">
  <div class="text-center my-5 mt-5 width-90">
    <div class="translate">
      <h1 class="home-title">CONTACT</h1>
      <p>Want to get in touch? <%= link_to "Send me an email", "mailto:info@antshaw.com" %>, <%= link_to "give me a ring", "tel:+447548241732" %> or hit me up on the socials:</p>
        <footer class="footer">
           <div class="container">
              <div class="footer">
                 <div class="footer-links">
                    <%= link_to 'https://www.instagram.com/antjjshaw', target: '_blank', rel:'noopener', id: "instagram-footer-link" do %>
                      <i class="fab fa-instagram"></i>
                    <% end %>
                    <%= link_to 'https://www.facebook.com/people/Anthony-Shaw/100011464090877/', target: '_blank', rel:'noopener', id: "facebook-footer-link" do %>
                      <i class="fab fa-facebook"></i>
                    <% end %>
                    <%= link_to 'https://www.twitter.com/anthonyjshaw', target: '_blank', rel:'noopener', id: "twitter-footer-link" do %>
                      <i class="fab fa-twitter"></i>
                    <% end %>
                    <%= link_to 'https://www.linkedin.com/in/anthonyjjshaw', target: '_blank', rel:'noopener', id: "linkedin-footer-link" do %>
                      <i class="fab fa-linkedin"></i>
                    <% end %>
                 </div>
              </div>
          </div>
      </footer>
    </div>
  </div>
</div>

</div>

app/views/pages/home.html.erb
<div class="flx-container">
  <div class="text-center my-5 mt-5">
    <div class='translate translate-mobile'>
      <h1 class='home-title'>Anthony Shaw</h1>
      <%# <%= image_tag "antshawlogo.svg", class: "logo" %>
        <h2>Creative Copywriter</h2>
      <%# <h3>Want more from your copy? Put Shaw on your copy.</h3> %>
    </div>
<div class="circle-container translate">
  <%= link_to "about" do %>
    <div class="circle-logo">About</div>
  <% end %>
  <%= link_to portfolio_path do %>
    <div class="circle-logo">Portfolio</div>
  <% end %>
   <!--
    <%= link_to "blog" do %>
  <div class="circle-logo">Blog</div>
   <% end %>
   --->
  <%= link_to "contact" do %>
    <div class="circle-logo">Contact</div>
  <% end %>
</div>
</div>
</div>

app/views/pages/home_copywriting.html.erb
<div class="flx-container">
  <div class="text-center my-5 mt-5">
    <div class='translate translate-mobile'>
      <h1 class='home-title'>ANTHONY SHAW</h1>
      <%# <%= image_tag "antshawlogo.svg", class: "logo" %>
	  <h2>COPYWRITING</h2>
    </div>
<div class="circle-container translate">
  <%= link_to "about" do %>
    <div class="circle-logo">About</div>
  <% end %>
  <%= link_to "portfolio" do %>
    <div class="circle-logo">Portfolio</div>
  <% end %>
   <!--
    <%= link_to "blog" do %>
  <div class="circle-logo">Blog</div>
   <% end %>
   --->
  <%= link_to "contact", id: "contact-button" do %>
    <div class="circle-logo">Contact</div>
  <% end %>
</div>
</div>
</div>

app/views/pages/portfolio.html.erb
<div class="flx-container">
  <div class="text-center my-5 mt-5">
    <div class="translate">
      <h1 class="home-title">PORTFOLIO</h1>
      <div id="arrow-box" class="arrow-box">
        <%= image_tag 'arrow.svg', alt: "Graphic of directional arrow box.", aria_label: "Click to see the portfolio."%>
      </div>
    </div>
  </div>
</div>
<hr/>
<div class="container-page">
<div id="portfolio-examples" class="portfolio-examples">
  <% @examples.each do |ad| %>
  <div class="project-section">

    <div class="<%= @examples.index(ad) % 2 === 0 ? "example-row-reverse" : "example-row" %> project-example"> 
    <div class= "image-container <%= @examples.index(ad) % 2 === 0 ? "flex-end" : "flex-start"%>">
      <% if ad[:link] %>
        <%= link_to ad[:link], alt: ad[:alt], rel: 'noopener', target: '_blank', aria_label: ad[:label] do %>
          <%= image_tag ad[:image_link], class: "project-image", alt: ad[:alt] %>
        <% end %>
        <% else %>
          <%= image_tag ad[:image_link], class: "project-image modal-image-check", data: {image_link: ad[:image_link]}, alt: ad[:alt] %>
      <% end %>
    </div>
    <div class="description-container">
      <h2 class="description-subheading">Brief</h2>
      <p><%= sanitize ad[:brief] %></p>
      <h2 class="description-subheading">Description</h2>
      <% if ad[:description].include? "\n\n" %>
        <% ad[:description].split("\n\n").each do |line| %>
          <p><%= sanitize line %></p>
        <% end %>
      <% else %>
        <p><%= sanitize ad[:description] %></p>
      <% end %>
    </div>
    </div>
  </div>
  <hr>
  <% end %>
</div>